#!/bin/sh
# $Id: mk,v 1.5 2014-10-21 20:11:10-07 - - $
cid $0 *.c testfile.in
mkc *.c
binarydump testfile.in >testbinary.out 2>&1
hexadecimaldump testfile.in >testhexadecimal.out 2>&1
mkpspdf Listing.src.ps *.c
mkpspdf -c Listing.out.ps *.out
