#!/usr/bin/perl
use strict;
use warnings;

while (my $file = <>) {
   for my $line (split '\n', $file) {
      print $line . "\n" if (!($line =~ /^ *$/) && !($line =~ /^#+/));
   }
}

#~ fromline 7
      #~ $line = chr (0xC0 | $ord >> 6) . chr (0x80 | $ord & 0x3F)
            #~ if $ord > 0x7F;
#~ foreach my $i (0 .. $#ARGV) {
	#~ print "$ARGV[$i]\n";
#~ }
#my $f = @_;
#open F, "< $f" or die "Can't open $f : $!";

#close F;
