#!/bin/sh
# $Id: mk,v 1.3 2014-10-24 17:31:19-07 - - $

show() {
   for file in $*
   do
      echo ::::::::::::::::::::::::::::::::
      echo $file
      echo ::::::::::::::::::::::::::::::::
      cat -v $file
   done
}

cat >test1.in <<__END__
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
tttttttttttttttttttttttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
__END__

phuffman.perl <test1.in >test1.out 2>&1

cat >test2.in <<__END__
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
eeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeee eeeeeeeeee
tttttttttttttttttttt tttttttttttttttttttt
aaaaaaaaaaaaaaaaaaaa
oooooooooooooooooooo
iiiiiiiiii
nnnnn
sssss
h
r
__END__

cid $0 phuffman.perl
phuffman.perl <test2.in >test2.out 2>&1
show test1.in test1.out test2.in test2.out >tests.lis
mkpspdf Listing.ps phuffman.perl tests.lis $0
